version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: swen-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: swen-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:

